version: '3'
services:

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: socketio_db
      MYSQL_ROOT_PASSWORD: root@123
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

  #Nodejs Service
  node:
    image: "node:alpine"
    container_name: nodejs_server
    restart: unless-stopped
    tty: true
#    user: "node"
#    working_dir: /home/node/app
    working_dir: /var/www/html
#    environment:
#      - NODE_ENV=production
    volumes:
#      - ./:/home/node/app
      - ./:/var/www/html
    expose:
      - "8081"
    ports:
      - "80:80"
#    command: "npm start"
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
